package apresentacao;

import entidades.Cliente;
import entidades.Conta;
import entidades.Movimentacao;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import negocio.NCliente;
import negocio.NConta;
import negocio.NMovimentacao;

/**
 *
 * @author rodolpho.repezza
 */
public class Saque extends javax.swing.JInternalFrame {
    
    JDesktopPane painelPrincipal;
    int id_conta;
    int id_cliente;

    /**
     * Creates new form Saque
     */
    public Saque() {
        initComponents();
    }

    Saque(JDesktopPane painelPrincipal) {
        this();
        this.painelPrincipal = painelPrincipal;
    }
    
    Saque(JDesktopPane painelPrincipal, int id_conta, int id_cliente) {
        this();
        this.painelPrincipal = painelPrincipal;
        this.id_cliente = id_cliente;
        this.id_conta = id_conta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Saque");
        setToolTipText("");

        jLabel1.setText("Valor:");

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(txtValor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(btnSacar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        try {
            float valor = Float.parseFloat(txtValor.getText());
            if(valor > 0) {
                NConta nc = new NConta();
                Conta c = nc.consultarID(id_conta);
                c.sacar(valor);
                nc.salvar(c);

                NCliente ncli = new NCliente();
                Cliente cli = ncli.consultarID(id_cliente);

                NMovimentacao nm = new NMovimentacao();
                Movimentacao mov = new Movimentacao();
                mov.setCliente(cli);
                mov.setConta(c);
                mov.setTipoMovimentacao(1);
                mov.setValor(valor);

                Date dataAtual = new Date();
                java.sql.Date data_mov = new java.sql.Date(dataAtual.getTime());
               
                mov.setData_hora(data_mov);

                nm.salvar(mov);

                JOptionPane.showMessageDialog(rootPane, "Saque no valor de R$" + valor + " efetuado com sucesso!");
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Valor inválido. Tente novamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
